baseurl: /R.4.01-DeveloppementWeb-JavaScript
permalink: /:categories/:title

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
  syntax_highlighter: disable

livereload: true